server:
  port: 9004
spring:
  application:
    name: consumer-feign
eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/ #单节点
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: consumer-feign #服务名
    prefer-ip-address: true #使用自己的ip地址注册而不是主机名