server:
  port: 4001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
          basedir: ./repo-config/ #缓存到本地的路径 执行的是new File("./repo-config/")操作
    bus:
      trace:
        enabled: true
#    stream:
#      kafka:
#        binder:
#          brokers: 192.168.10.130:9092
  rabbitmq:
    addresses: 192.168.10.130:5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/ #单节点
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: config-server #服务名
    prefer-ip-address: true #使用自己的ip地址注册而不是主机名
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh